### ISSUE TITLE
Example 3: Classification with MLP:, more options = option criterion() not allowed

### ISSUE THREAD

**Issue by LPecht** [mdroste/stata-pylearn#1]
* Load data
            webuse iris, clear
 * Generate a training flag, marking approx 30% of dataset as training
            gen training = runiform()<0.3
  * Run model with one hidden layer, mess with options
            pymlp iris seplen sepwid petlen petwid if training==1, type(classify) criterion(entropy) alpha(0.0005) hidden_layer_sizes(5)
option criterion() not allowed
r(198);

**Comment by mdroste** [comment]
Hey - thanks for pointing this out! You found a (significant) typo in the example provided with the internal documentation - the criterion() option really isn't allowed for pymlp, and the example is wrong! I've fixed this in the version I'll push today.

**Comment by mdroste** [comment]
(I happen to be flying right now and JetBlue's in-flight wifi doesn't let me push to GitHub using GitHub Desktop - I'll just push the latest version later today @LPecht)

**Comment by LPecht** [comment]
sounds greats, I have found a second bug. Maybe you can fixed them both before commit. thks.
